version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: django
    command: gunicorn --config gunicorn-cfg.py main.wsgi
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/code
    networks: 
      - main
      
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: dev/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx/dev/dev.conf:/etc/nginx/nginx.conf:ro
      - ./backend/staticfiles:/usr/src/app/assets
    depends_on:
      - web
    networks:
      - main

networks:
  main:
    driver: bridge