version: "3.7"

services:
  django:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: django
    command: python manage.py runserver
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/code
      
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: dev/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx/dev/dev.conf:/etc/nginx/nginx.conf:ro
      - ./data:/data  
